assert(SMODS.load_file("modules/assets.lua"))()
assert(SMODS.load_file("modules/utils.lua"))()
assert(SMODS.load_file("modules/jokers.lua"))()
assert(SMODS.load_file("modules/challenges.lua"))()
--assert(SMODS.load_file("modules/hooks.lua"))()