[manifest]
version = "1.0.0"
priority = 20000

[[patches]]
[patches.pattern]
target = "functions/button_callbacks.lua"
pattern = "((G.GAME.dollars-G.GAME.bankrupt_at) - G.GAME.current_round.reroll_cost < 0) and G.GAME.current_round.reroll_cost ~= 0"
position = "after"
payload = '''
or hyper_thcief_call()
'''
match_indent = true
times = 1

[[patches]]
[patches.pattern] # taken from Balt's Warehouse
target = "engine/sprite.lua"
pattern = "love.graphics.setColor(overlay or G.BRUTE_OVERLAY or G.C.WHITE)"
position = "after"
payload = '''
if self.sideways then
	love.graphics.rotate(math.pi/2)
	local transform = self.VT or self.T
    love.graphics.translate(0, -transform.w*G.TILESIZE*1.75)
end
'''
match_indent = false
times = 1

[[patches]]
[patches.pattern] 
target = "engine/card.lua"
pattern = "self.ARGS.send_to_shader, nil, self.children.center"
position = "after"
payload = '''
, nil, (((self.config.center_key=='j_hypr_widescreen') and math.pi/2) or 0)
'''
match_indent = false
times = 1
