[manifest]
version = "1.0.0"
dump_lua = true
priority = 20000

[[patches]]
[patches.pattern]
target = "functions/button_callbacks.lua"
pattern = "((G.GAME.dollars-G.GAME.bankrupt_at) - G.GAME.current_round.reroll_cost < 0) and G.GAME.current_round.reroll_cost ~= 0"
position = "after"
payload = '''
or hyper_thcief_call()
'''
match_indent = true
times = 1